export interface CourseItem {
  id: string
  type: "youtube" | "article" | "github"
  title: string
  description: string
  url: string
  tags: string[] // New: Tags for filtering
}

export interface Topic {
  id: string
  name: string
  items: CourseItem[]
  colorDot: string // Tailwind color class for the small dot in the select dropdown
  headerBg: string // Tailwind background color class for the topic header
  headerText: string // Tailwind text color class for the topic header
  image: string // Image URL for the topic header
  difficulty: "easy" | "medium" | "hard" // New: Difficulty level
  estimatedTime: string // New: Estimated time to complete
}

export const topics: Topic[] = [
  {
    id: "ml",
    name: "Machine Learning (ML)",
    colorDot: "bg-purple-500",
    headerBg: "bg-purple-700",
    headerText: "text-white",
    image: "/placeholder.svg?height=100&width=100&text=ML", // Updated image
    difficulty: "medium",
    estimatedTime: "40-60 hours",
    items: [
      {
        id: "ml-1",
        type: "youtube",
        title: "Machine Learning Crash Course (10 hrs)",
        description: "Full intro covering Linear/Logistic Regression and Decision Trees.",
        url: "https://www.youtube.com/watch?v=GwIo3gDZCVQ",
        tags: ["beginner", "ml", "python"],
      },
      {
        id: "ml-2",
        type: "article",
        title: "Hands‑on with scikit‑learn",
        description: "Tutorial using real datasets with scikit‑learn pipelines.",
        url: "https://scikit-learn.org/stable/tutorial/basic/tutorial.html",
        tags: ["beginner", "ml", "python"],
      },
      {
        id: "ml-3",
        type: "github",
        title: "Awesome Public Datasets",
        description: "Collection of high‑quality, real‑world ML datasets.",
        url: "https://github.com/awesomedata/awesome-public-datasets",
        tags: ["resource", "ml"],
      },
      {
        id: "ml-4",
        type: "youtube",
        title: "Random Forests Explained",
        description: "How random forests work in ensemble learning.",
        url: "https://www.youtube.com/watch?v=J4Wdy0Wc_xQ",
        tags: ["intermediate", "ml", "algorithm"],
      },
      {
        id: "ml-5",
        type: "article",
        title: "Gradient Boosting Basics",
        description: "XGBoost, LightGBM and boosting theory.",
        url: "https://www.datacamp.com/community/tutorials/gradient-boosting-machine",
        tags: ["intermediate", "ml", "algorithm"],
      },
      {
        id: "ml-6",
        type: "github",
        title: "ML‑From‑Scratch",
        description: "Implement ML algorithms in Python from the ground up.",
        url: "https://github.com/eriklindernoren/ML-From-Scratch",
        tags: ["advanced", "ml", "python"],
      },
      {
        id: "ml-7",
        type: "youtube",
        title: "Support Vector Machines (SVM)",
        description: "Mathematical intuition and coding example.",
        url: "https://www.youtube.com/watch?v=efR1C6CvhmE",
        tags: ["intermediate", "ml", "algorithm"],
      },
      {
        id: "ml-8",
        type: "article",
        title: "Unsupervised Learning: Clustering & PCA",
        description: "Techniques and use‑cases in practice.",
        url: "https://towardsdatascience.com/unsupervised-learning-clustering-and-pca-9cae0e7a7871",
        tags: ["intermediate", "ml", "data-analysis"],
      },
      {
        id: "ml-9",
        type: "github",
        title: "Awesome‑ML‑papers",
        description: "Annotated list of important machine learning research papers.",
        url: "https://github.com/theouterrim/awesome-machine-learning-papers",
        tags: ["resource", "ml", "research"],
      },
      {
        id: "ml-10",
        type: "youtube",
        title: "Reinforcement Learning Basics",
        description: "Q‑learning and policy gradients explained.",
        url: "https://www.youtube.com/watch?v=2pWv7GOvuf0",
        tags: ["advanced", "ml", "ai"],
      },
      {
        id: "ml-11",
        type: "article",
        title: "Bias‑Variance Tradeoff",
        description: "How to diagnose and optimize generalization.",
        url: "https://machinelearningmastery.com/gentle-introduction-to-bias-variance-trade-off-in-machine-learning/",
        tags: ["intermediate", "ml", "theory"],
      },
      {
        id: "ml-12",
        type: "github",
        title: "OpenAI Gym Examples",
        description: "Reinforcement learning environments & baselines.",
        url: "https://github.com/openai/gym",
        tags: ["advanced", "ml", "ai", "python"],
      },
      {
        id: "ml-13",
        type: "youtube",
        title: "Feature Engineering Techniques",
        description: "Create better features for real datasets.",
        url: "https://www.youtube.com/watch?v=GaGr-nYKPbs",
        tags: ["intermediate", "data-analysis", "ml"],
      },
      {
        id: "ml-14",
        type: "article",
        title: "Cross‑Validation Methods",
        description: "k‑fold, stratified, time series and more.",
        url: "https://scikit-learn.org/stable/modules/cross_validation.html",
        tags: ["intermediate", "ml", "statistics"],
      },
      {
        id: "ml-15",
        type: "github",
        title: "fast‑ai Tutorials",
        description: "Code repo accompanying fast.ai courses.",
        url: "https://github.com/fastai/fastai",
        tags: ["resource", "ml", "deep-learning"],
      },
      {
        id: "ml-16",
        type: "youtube",
        title: "Handling Imbalanced Data",
        description: "Techniques like SMOTE and resampling.",
        url: "https://www.youtube.com/watch?v=hc3fGId_kDA",
        tags: ["advanced", "ml", "data-analysis"],
      },
      {
        id: "ml-17",
        type: "article",
        title: "Interpretability: SHAP & LIME",
        description: "Explainable AI techniques in practice.",
        url: "https://christophm.github.io/interpretable-ml-book/shap.html",
        tags: ["advanced", "ml", "ai"],
      },
      {
        id: "ml-18",
        type: "github",
        title: "Explainable‑AI‑Toolkit",
        description: "Open‑source tools for model interpretability.",
        url: "https://github.com/explainable-ai/interpret",
        tags: ["resource", "ml", "ai"],
      },
      {
        id: "ml-19",
        type: "youtube",
        title: "Transfer Learning in ML",
        description: "Fine‑tuning pre‑trained models for new tasks.",
        url: "https://www.youtube.com/watch?v=tiARVIOZnmY",
        tags: ["advanced", "ml", "deep-learning"],
      },
      {
        id: "ml-20",
        type: "article",
        title: "ML in Production: MLOps",
        description: "Deploying models, monitoring & pipelines.",
        url: "https://mlops.community/",
        tags: ["advanced", "ml", "devops"],
      },
      {
        id: "ml-21",
        type: "github",
        title: "Kubeflow Examples",
        description: "End‑to‑end ML pipelines on Kubernetes.",
        url: "https://github.com/kubeflow/examples",
        tags: ["advanced", "ml", "devops", "cloud"],
      },
      {
        id: "ml-22",
        type: "article",
        title: "Coursera: ML Specialization (paid)",
        description: "Andrew Ng’s paid ML specialization.",
        url: "https://www.coursera.org/specializations/machine-learning",
        tags: ["resource", "ml", "paid"],
      },
    ],
  },
  {
    id: "dl",
    name: "Deep Learning (DL)",
    colorDot: "bg-pink-500",
    headerBg: "bg-pink-700",
    headerText: "text-white",
    image: "/placeholder.svg?height=100&width=100&text=DL", // Updated image
    difficulty: "hard",
    estimatedTime: "50-70 hours",
    items: [
      {
        id: "dl-1",
        type: "youtube",
        title: "Neural Networks from Scratch",
        description: "Build a neural network from the ground up.",
        url: "https://www.youtube.com/watch?v=Wo5dWI_2y_o",
        tags: ["beginner", "dl", "python"],
      },
      {
        id: "dl-2",
        type: "article",
        title: "CNNs Explained Visually",
        description: "Intuitive guide to convolutional neural networks.",
        url: "https://towardsdatascience.com/a-comprehensive-guide-to-convolutional-neural-networks-cnn-f3b2d3fd3f5c",
        tags: ["intermediate", "dl", "computer-vision"],
      },
      {
        id: "dl-3",
        type: "github",
        title: "PyTorch Vision Examples",
        description: "Image classification, transfer learning examples.",
        url: "https://github.com/pytorch/examples/tree/main/vision",
        tags: ["intermediate", "dl", "pytorch", "computer-vision"],
      },
      {
        id: "dl-4",
        type: "youtube",
        title: "Recurrent Neural Networks (RNNs)",
        description: "Understanding sequence models & LSTM.",
        url: "https://www.youtube.com/watch?v=WCUNPb‑ObYE",
        tags: ["intermediate", "dl", "nlp"],
      },
      {
        id: "dl-5",
        type: "article",
        title: "GANs: Generative Adversarial Networks",
        description: "How GANs work and typical applications.",
        url: "https://developers.google.com/machine-learning/gan",
        tags: ["advanced", "dl", "generative-ai"],
      },
      {
        id: "dl‑6",
        type: "github",
        title: "TensorFlow Models",
        description: "Official TF‑examples: computer vision, NLP.",
        url: "https://github.com/tensorflow/models",
        tags: ["intermediate", "dl", "tensorflow"],
      },
      {
        id: "dl‑7",
        type: "youtube",
        title: "Transformers: Attention Mechanism",
        description: "Self‑attention and BERT explained.",
        url: "https://www.youtube.com/watch?v=iDulhoQ2pro",
        tags: ["advanced", "dl", "nlp"],
      },
      {
        id: "dl‑8",
        type: "article",
        title: "Sequence‑to‑Sequence Models",
        description: "Machine translation and summarization basics.",
        url: "https://jalammar.github.io/illustrated-transformer/",
        tags: ["advanced", "dl", "nlp"],
      },
      {
        id: "dl‑9",
        type: "github",
        title: "HuggingFace Transformers",
        description: "State‑of‑the‑art NLP model implementations.",
        url: "https://github.com/huggingface/transformers",
        tags: ["resource", "dl", "nlp"],
      },
      {
        id: "dl‑10",
        type: "youtube",
        title: "Autoencoders & Variational Autoencoders",
        description: "Dimensionality reduction and generation.",
        url: "https://www.youtube.com/watch?v=9zKuYvjFFS8",
        tags: ["advanced", "dl", "generative-ai"],
      },
      {
        id: "dl‑11",
        type: "article",
        title: "Deep Learning with PyTorch",
        description: "PyTorch best practices and tutorials.",
        url: "https://pytorch.org/tutorials/",
        tags: ["intermediate", "dl", "pytorch"],
      },
      {
        id: "dl‑12",
        type: "github",
        title: "fast‑ai Course Code",
        description: "Course notebooks from fast.ai DL series.",
        url: "https://github.com/fastai/fastbook",
        tags: ["resource", "dl", "pytorch"],
      },
      {
        id: "dl‑13",
        type: "youtube",
        title: "Advanced CNN Architectures",
        description: "ResNet, DenseNet, Inception layers explained.",
        url: "https://www.youtube.com/watch?v=GhHCdG4Obzg",
        tags: ["advanced", "dl", "computer-vision"],
      },
      {
        id: "dl‑14",
        type: "article",
        title: "Attention and Self‑Attention",
        description: "Key ideas in modern NLP architectures.",
        url: "https://lilianweng.github.io/lil-log/2018/06/24/attention-attention.html",
        tags: ["advanced", "dl", "nlp"],
      },
      {
        id: "dl‑15",
        type: "github",
        title: "Awesome Deep Learning",
        description: "Curated list of frameworks, tutorials & resources.",
        url: "https://github.com/ChristosChristofidis/awesome-deep-learning",
        tags: ["resource", "dl"],
      },
      {
        id: "dl‑16",
        type: "youtube",
        title: "Deep Reinforcement Learning",
        description: "Deep Q‑Networks and policy optimization.",
        url: "https://www.youtube.com/watch?v=YCc2SbGss3E",
        tags: ["advanced", "dl", "ai"],
      },
      {
        id: "dl‑17",
        type: "article",
        title: "Ethics in AI & Deep Learning",
        description: "Bias, fairness, and privacy concerns.",
        url: "https://ai.google/responsibility/",
        tags: ["theory", "ai", "ethics"],
      },
      {
        id: "dl‑18",
        type: "github",
        title: "DeepMind Lab",
        description: "QA envs for RL research.",
        url: "https://github.com/deepmind/lab",
        tags: ["resource", "ai", "research"],
      },
      {
        id: "dl‑19",
        type: "youtube",
        title: "Deploying DL Models",
        description: "Serving TensorFlow and PyTorch models at scale.",
        url: "https://www.youtube.com/watch?v=5X_73_tvGfs",
        tags: ["advanced", "dl", "devops"],
      },
      {
        id: "dl‑20",
        type: "article",
        title: "Coursera: Deep Learning Specialization (paid)",
        description: "Andrew Ng’s paid DL specialization.",
        url: "https://www.coursera.org/specializations/deep-learning",
        tags: ["resource", "dl", "paid"],
      },
      {
        id: "dl‑21",
        type: "github",
        title: "ONNX Models",
        description: "Interoperable open format for AI models.",
        url: "https://github.com/onnx/models",
        tags: ["resource", "dl", "devops"],
      },
    ],
  },
  {
    id: "fullstack",
    name: "Web Development (Fullstack)",
    colorDot: "bg-green-500",
    headerBg: "bg-green-700",
    headerText: "text-white",
    image: "/placeholder.svg?height=100&width=100&text=WebDev", // Updated image
    difficulty: "medium",
    estimatedTime: "60-80 hours",
    items: [
      {
        id: "fullstack-1",
        type: "youtube",
        title: "React & Next.js 14 Full Course",
        description: "HTML/CSS/JS foundations → React → APIs → Hosting & Auth.",
        url: "https://www.youtube.com/watch?v=wm5gMKuwSYk",
        tags: ["beginner", "frontend", "backend", "nextjs", "react"],
      },
      {
        id: "fullstack-2",
        type: "article",
        title: "REST API Design Handbook",
        description: "Best practices for designing web APIs.",
        url: "https://restfulapi.net/",
        tags: ["intermediate", "backend", "api"],
      },
      {
        id: "fullstack-3",
        type: "github",
        title: "next-auth-starter",
        description: "Boilerplate showing basics of auth in a Next.js full‑stack app.",
        url: "https://github.com/vercel/nextjs-auth-starter",
        tags: ["resource", "nextjs", "auth"],
      },
      {
        id: "fullstack-4",
        type: "youtube",
        title: "Full‑Stack MERN Course",
        description: "MongoDB, Express, React, Node.js full project.",
        url: "https://www.youtube.com/watch?v=kV6tL-UqCfk",
        tags: ["intermediate", "mern", "backend", "frontend"],
      },
      {
        id: "fullstack-5",
        type: "article",
        title: "GraphQL vs REST",
        description: "Comparative guide with pros/cons.",
        url: "https://www.howtographql.com/",
        tags: ["intermediate", "api"],
      },
      {
        id: "fullstack-6",
        type: "github",
        title: "Apollo‑Server‑Starter",
        description: "GraphQL server setup with Node.js.",
        url: "https://github.com/apollographql/apollo-server",
        tags: ["resource", "graphql", "backend"],
      },
      {
        id: "fullstack-7",
        type: "youtube",
        title: "Tailwind CSS Crash Course",
        description: "Modern utility‑first CSS framework.",
        url: "https://www.youtube.com/watch?v=UBOj6rqRUME",
        tags: ["beginner", "frontend", "css"],
      },
      {
        id: "fullstack-8",
        type: "article",
        title: "State Management with Redux",
        description: "Core concepts of Redux and modern patterns.",
        url: "https://redux.js.org/",
        tags: ["intermediate", "frontend", "react"],
      },
      {
        id: "fullstack-9",
        type: "github",
        title: "Redux Toolkit Example",
        description: "Standard Redux tooling and patterns.",
        url: "https://github.com/reduxjs/redux-toolkit",
        tags: ["resource", "frontend", "react"],
      },
      {
        id: "fullstack-10",
        type: "youtube",
        title: "Serverless with Next.js and Vercel",
        description: "API routes & edge functions deployment.",
        url: "https://www.youtube.com/watch?v=1WmNXEVia8I",
        tags: ["intermediate", "nextjs", "serverless", "cloud"],
      },
      {
        id: "fullstack-11",
        type: "article",
        title: "Authentication: OAuth vs JWT",
        description: "Securing full‑stack apps effectively.",
        url: "https://auth0.com/blog/oauth-2-the-invisible-handshake/",
        tags: ["intermediate", "security", "auth"],
      },
      {
        id: "fullstack-12",
        type: "github",
        title: "Next.js Fullstack Boilerplate",
        description: "Full app with SSR, auth, and API.",
        url: "https://github.com/vercel/next.js/tree/canary/examples/with-auth",
        tags: ["resource", "nextjs", "fullstack"],
      },
      {
        id: "fullstack-13",
        type: "youtube",
        title: "Dockerizing a Full‑Stack App",
        description: "Containerizing backend and frontend services.",
        url: "https://www.youtube.com/watch?v=Gjnup‑PD5W4",
        tags: ["advanced", "devops", "docker"],
      },
      {
        id: "fullstack-14",
        type: "article",
        title: "CI/CD for Web Apps",
        description: "Automated pipelines for full‑stack deployment.",
        url: "https://circleci.com/blog/continuous-integration-cd-for-web-dev/",
        tags: ["advanced", "devops", "cicd"],
      },
      {
        id: "fullstack-15",
        type: "github",
        title: "Awesome Full‑Stack Projects",
        description: "Inspiration and code for end‑to‑end apps.",
        url: "https://github.com/karan/Projects",
        tags: ["resource", "project"],
      },
      {
        id: "fullstack-16",
        type: "youtube",
        title: "Progressive Web App (PWA)",
        description: "Building PWA with Next.js & service workers.",
        url: "https://www.youtube.com/watch?v=xlS_gC-Q0vg",
        tags: ["advanced", "frontend", "pwa"],
      },
      {
        id: "fullstack-17",
        type: "article",
        title: "Web Accessibility (a11y)",
        description: "Best practices for inclusive web design.",
        url: "https://webaim.org/intro/",
        tags: ["frontend", "ux", "accessibility"],
      },
      {
        id: "fullstack-18",
        type: "github",
        title: "a11y‑examples",
        description: "Accessible components & patterns.",
        url: "https://github.com/Alhadis/a11y-examples",
        tags: ["resource", "frontend", "accessibility"],
      },
      {
        id: "fullstack-19",
        type: "youtube",
        title: "Real‑Time with WebSockets",
        description: "Live chat & data updates in full‑stack apps.",
        url: "https://www.youtube.com/watch?v=vQjiN8Qgs3c",
        tags: ["advanced", "backend", "real-time"],
      },
      {
        id: "fullstack-20",
        type: "article",
        title: "Scalable Databases for Web Apps",
        description: "SQL vs NoSQL, sharding, scaling strategies.",
        url: "https://www.digitalocean.com/community/tutorials/sql-vs-nosql-when-to-use-which",
        tags: ["advanced", "backend", "database"],
      },
      {
        id: "fullstack-21",
        type: "github",
        title: "Awesome Micro‑Frontends",
        description: "Patterns and code for micro‑frontend architecture.",
        url: "https://github.com/micro-frontends",
        tags: ["advanced", "frontend", "architecture"],
      },
      {
        id: "fullstack-22",
        type: "article",
        title: "Udemy: Fullstack 開發 Complete Guide (paid)",
        description: "Paid comprehensive course covering full‑stack.",
        url: "https://www.udemy.com/course/the-complete-web-developer-guide/",
        tags: ["resource", "fullstack", "paid"],
      },
    ],
  },
  {
    id: "dsa",
    name: "Data Structures & Algorithms",
    colorDot: "bg-blue-500",
    headerBg: "bg-blue-700",
    headerText: "text-white",
    image: "/placeholder.svg?height=100&width=100&text=DSA", // Updated image
    difficulty: "hard",
    estimatedTime: "30-50 hours",
    items: [
      {
        id: "dsa-1",
        type: "youtube",
        title: "DSA Crash Course",
        description: "Learn DSA from scratch.",
        url: "https://www.youtube.com/watch?v=8hly31xKli0",
        tags: ["beginner", "dsa", "fundamentals"],
      },
      {
        id: "dsa-2",
        type: "article",
        title: "Big O Cheat Sheet",
        description: "Complexity reference for algorithms.",
        url: "https://www.bigocheatsheet.com/",
        tags: ["resource", "dsa", "theory"],
      },
      {
        id: "dsa-3",
        type: "github",
        title: "The Algorithms",
        description: "Community repo of classic algorithms.",
        url: "https://github.com/TheAlgorithms/Python",
        tags: ["resource", "dsa", "python"],
      },
      {
        id: "dsa-4",
        type: "youtube",
        title: "Trees & Graphs",
        description: "Interview-focused problems.",
        url: "https://www.youtube.com/watch?v=oBt53YbR9Kk",
        tags: ["intermediate", "dsa", "interview-prep"],
      },
      {
        id: "dsa-5",
        type: "article",
        title: "Greedy vs DP",
        description: "Strategy comparison in DSA.",
        url: "https://www.geeksforgeeks.org/dynamic-programming/",
        tags: ["intermediate", "dsa", "algorithm"],
      },
      {
        id: "dsa-6",
        type: "github",
        title: "Neetcode DSA patterns",
        description: "Categorized problems with code.",
        url: "https://github.com/neetcode-gh/leetcode",
        tags: ["resource", "dsa", "interview-prep"],
      },
      {
        id: "dsa-7",
        type: "youtube",
        title: "Recursion & Backtracking",
        description: "Core recursion tricks.",
        url: "https://www.youtube.com/watch?v=lmbVSB8O8ps",
        tags: ["intermediate", "dsa", "algorithm"],
      },
      {
        id: "dsa-8",
        type: "article",
        title: "Heap & Priority Queues",
        description: "Theory and application.",
        url: "https://www.hackerearth.com/practice/data-structures/",
        tags: ["intermediate", "dsa", "data-structure"],
      },
      {
        id: "dsa-9",
        type: "github",
        title: "Leetcode Patterns",
        description: "Topic-wise practice map.",
        url: "https://github.com/SeanPrashad/leetcode-patterns",
        tags: ["resource", "dsa", "interview-prep"],
      },
      {
        id: "dsa-10",
        type: "youtube",
        title: "Top 100 Interview Qs",
        description: "Must-solve coding questions.",
        url: "https://www.youtube.com/watch?v=edpjsJmWN5o",
        tags: ["advanced", "dsa", "interview-prep"],
      },
    ],
  },

  {
    id: "system-design",
    name: "System Design Basics",
    colorDot: "bg-yellow-500",
    headerBg: "bg-yellow-700",
    headerText: "text-white",
    image: "/placeholder.svg?height=100&width=100&text=SysDesign", // Updated image
    difficulty: "medium",
    estimatedTime: "20-30 hours",
    items: [
      {
        id: "sys-1",
        type: "youtube",
        title: "System Design Primer",
        description: "High-level intro to large-scale systems.",
        url: "https://www.youtube.com/watch?v=UzLMhqg3_Wc",
        tags: ["beginner", "system-design", "architecture"],
      },
      {
        id: "sys-2",
        type: "article",
        title: "Load Balancer vs Proxy",
        description: "Understand infra basics.",
        url: "https://nginx.com/blog/load-balancing-primer/",
        tags: ["intermediate", "system-design", "networking"],
      },
      {
        id: "sys-3",
        type: "github",
        title: "System Design Repo",
        description: "Open-source prep guide.",
        url: "https://github.com/donnemartin/system-design-primer",
        tags: ["resource", "system-design", "interview-prep"],
      },
      {
        id: "sys-4",
        type: "youtube",
        title: "Design Twitter",
        description: "End-to-end Twitter clone system.",
        url: "https://www.youtube.com/watch?v=3QhU9jd03a0",
        tags: ["advanced", "system-design", "case-study"],
      },
      {
        id: "sys-5",
        type: "article",
        title: "CAP Theorem Simplified",
        description: "Consistency vs availability.",
        url: "https://www.educative.io/blog/cap-theorem",
        tags: ["intermediate", "system-design", "database"],
      },
      {
        id: "sys-6",
        type: "github",
        title: "High-Scalability Links",
        description: "Reading archive for SD.",
        url: "https://github.com/binhnguyennus/awesome-scalability",
        tags: ["resource", "system-design", "scalability"],
      },
      {
        id: "sys-7",
        type: "youtube",
        title: "Caching Explained",
        description: "Redis, Memcached, CDNs.",
        url: "https://www.youtube.com/watch?v=R9PqjMSNfkU",
        tags: ["intermediate", "system-design", "performance"],
      },
      {
        id: "sys-8",
        type: "article",
        title: "Event-Driven Architecture",
        description: "Kafka, queues, and real-time.",
        url: "https://aws.amazon.com/event-driven-architecture/",
        tags: ["advanced", "system-design", "architecture"],
      },
      {
        id: "sys-9",
        type: "github",
        title: "Scalable Architecture Diagrams",
        description: "System blueprints.",
        url: "https://github.com/realpython/python-systems-design",
        tags: ["resource", "system-design", "architecture"],
      },
      {
        id: "sys-10",
        type: "youtube",
        title: "Design YouTube",
        description: "Video service infra.",
        url: "https://www.youtube.com/watch?v=FSfN2q_G3lo",
        tags: ["advanced", "system-design", "case-study"],
      },
    ],
  },
  {
    id: "os",
    name: "Operating Systems",
    colorDot: "bg-teal-500",
    headerBg: "bg-teal-700",
    headerText: "text-white",
    image: "/placeholder.svg?height=100&width=100&text=OS", // Updated image
    difficulty: "medium",
    estimatedTime: "25-40 hours",
    items: [
      {
        id: "os-1",
        type: "youtube",
        title: "OS Crash Course",
        description: "Basics of OS concepts.",
        url: "https://www.youtube.com/watch?v=26QPDBe-NB8",
        tags: ["beginner", "os", "fundamentals"],
      },
      {
        id: "os-2",
        type: "article",
        title: "Processes vs Threads",
        description: "Key differences and use-cases.",
        url: "https://www.geeksforgeeks.org/difference-between-process-and-thread/",
        tags: ["intermediate", "os", "concurrency"],
      },
      {
        id: "os-3",
        type: "github",
        title: "MIT 6.828 Lab Code",
        description: "xv6 OS from scratch.",
        url: "https://github.com/mit-pdos/xv6-public",
        tags: ["advanced", "os", "project"],
      },
      {
        id: "os-4",
        type: "youtube",
        title: "Virtual Memory Explained",
        description: "Paging and segmentation.",
        url: "https://www.youtube.com/watch?v=wx7l4M8KxF8",
        tags: ["intermediate", "os", "memory"],
      },
      {
        id: "os-5",
        type: "article",
        title: "File System Basics",
        description: "Common structures used.",
        url: "https://www.geeksforgeeks.org/file-systems/",
        tags: ["beginner", "os", "storage"],
      },
      {
        id: "os-6",
        type: "github",
        title: "Operating Systems Concepts",
        description: "Open resources and examples.",
        url: "https://github.com/CodeSystem2022/OS",
        tags: ["resource", "os"],
      },
      {
        id: "os-7",
        type: "youtube",
        title: "CPU Scheduling Algorithms",
        description: "All major scheduling policies.",
        url: "https://www.youtube.com/watch?v=KtuQpQwlmEc",
        tags: ["intermediate", "os", "algorithm"],
      },
      {
        id: "os-8",
        type: "article",
        title: "Deadlock Avoidance",
        description: "Banker’s algorithm, etc.",
        url: "https://www.javatpoint.com/os-deadlock",
        tags: ["advanced", "os", "concurrency"],
      },
      {
        id: "os-9",
        type: "github",
        title: "OSTep Book Source",
        description: "Code and references from the OS textbook.",
        url: "https://github.com/remzi-arpacidusseau/ostep-code",
        tags: ["resource", "os", "book"],
      },
      {
        id: "os-10",
        type: "youtube",
        title: "Interrupts in OS",
        description: "How OS handles external events.",
        url: "https://www.youtube.com/watch?v=K8g4Ae5yEJ8",
        tags: ["intermediate", "os", "hardware"],
      },
    ],
  },

  {
    id: "dbms",
    name: "Database Systems",
    colorDot: "bg-orange-500",
    headerBg: "bg-orange-700",
    headerText: "text-white",
    image: "/placeholder.svg?height=100&width=100&text=DBMS", // Updated image
    difficulty: "easy",
    estimatedTime: "20-35 hours",
    items: [
      {
        id: "dbms-1",
        type: "youtube",
        title: "Intro to DBMS",
        description: "Overview of databases and data models.",
        url: "https://www.youtube.com/watch?v=ztHopE5Wnpc",
        tags: ["beginner", "database", "sql"],
      },
      {
        id: "dbms-2",
        type: "article",
        title: "SQL vs NoSQL",
        description: "When and why to use each.",
        url: "https://www.mongodb.com/sql-vs-nosql",
        tags: ["intermediate", "database", "nosql"],
      },
      {
        id: "dbms-3",
        type: "github",
        title: "DBMS Mini Projects",
        description: "Sample SQL-based apps.",
        url: "https://github.com/topics/dbms-project",
        tags: ["resource", "database", "project"],
      },
      {
        id: "dbms-4",
        type: "youtube",
        title: "Joins in SQL",
        description: "Types of joins explained.",
        url: "https://www.youtube.com/watch?v=9yeOJ0ZMUYw",
        tags: ["beginner", "sql"],
      },
      {
        id: "dbms-5",
        type: "article",
        title: "Normalization Forms",
        description: "1NF, 2NF, 3NF examples.",
        url: "https://www.geeksforgeeks.org/database-normalization/",
        tags: ["intermediate", "database", "theory"],
      },
      {
        id: "dbms-6",
        type: "github",
        title: "Awesome SQL Tricks",
        description: "Handy SQL scripts.",
        url: "https://github.com/danistefanovic/build-your-own-x#database",
        tags: ["resource", "sql"],
      },
      {
        id: "dbms-7",
        type: "youtube",
        title: "ACID Properties",
        description: "Transactions and consistency.",
        url: "https://www.youtube.com/watch?v=H6JFLqP0D-c",
        tags: ["advanced", "database", "theory"],
      },
      {
        id: "dbms-8",
        type: "article",
        title: "Indexing in Databases",
        description: "B-trees and hash indexes.",
        url: "https://use-the-index-luke.com/",
        tags: ["advanced", "database", "performance"],
      },
      {
        id: "dbms-9",
        type: "github",
        title: "SQL Zoo",
        description: "Interactive SQL learning platform.",
        url: "https://github.com/danistefanovic/sqlzoo",
        tags: ["resource", "sql", "practice"],
      },
      {
        id: "dbms-10",
        type: "youtube",
        title: "ER Diagrams",
        description: "Entity-relationship modeling.",
        url: "https://www.youtube.com/watch?v=QpdhBUYk7Kk",
        tags: ["beginner", "database", "design"],
      },
    ],
  },

  {
    id: "git",
    name: "Version Control with Git",
    colorDot: "bg-red-500",
    headerBg: "bg-red-700",
    headerText: "text-white",
    image: "/placeholder.svg?height=100&width=100&text=Git", // Updated image
    difficulty: "easy",
    estimatedTime: "10-15 hours",
    items: [
      {
        id: "git-1",
        type: "youtube",
        title: "Git & GitHub for Beginners",
        description: "Intro to version control basics.",
        url: "https://www.youtube.com/watch?v=RGOj5yH7evk",
        tags: ["beginner", "git", "github"],
      },
      {
        id: "git-2",
        type: "article",
        title: "Git Cheat Sheet",
        description: "Common Git commands.",
        url: "https://education.github.com/git-cheat-sheet-education.pdf",
        tags: ["resource", "git"],
      },
      {
        id: "git-3",
        type: "github",
        title: "GitHub Actions Examples",
        description: "CI/CD workflows in GitHub.",
        url: "https://github.com/actions/starter-workflows",
        tags: ["intermediate", "github", "cicd"],
      },
      {
        id: "git-4",
        type: "youtube",
        title: "Git Internals",
        description: "How Git stores data under the hood.",
        url: "https://www.youtube.com/watch?v=1ffBJ4sVUb4",
        tags: ["advanced", "git", "theory"],
      },
      {
        id: "git-5",
        type: "article",
        title: "Branching Strategies",
        description: "Feature branching, Git Flow.",
        url: "https://nvie.com/posts/a-successful-git-branching-model/",
        tags: ["intermediate", "git", "workflow"],
      },
      {
        id: "git-6",
        type: "github",
        title: "Open Source Repos to Contribute",
        description: "Find beginner-friendly projects.",
        url: "https://github.com/MunGell/awesome-for-beginners",
        tags: ["resource", "open-source"],
      },
      {
        id: "git-7",
        type: "youtube",
        title: "Resolving Merge Conflicts",
        description: "Step-by-step walkthrough.",
        url: "https://www.youtube.com/watch?v=x5J8lO-j5Go",
        tags: ["beginner", "git", "troubleshooting"],
      },
      {
        id: "git-8",
        type: "article",
        title: "Rebase vs Merge",
        description: "Comparison and when to use which.",
        url: "https://www.git-scm.com/docs/git-rebase",
        tags: ["intermediate", "git", "workflow"],
      },
      {
        id: "git-9",
        type: "github",
        title: "Git Exercises",
        description: "Practice problems for Git.",
        url: "https://github.com/bobbyiliev/git-exercises",
        tags: ["resource", "git", "practice"],
      },
      {
        id: "git-10",
        type: "youtube",
        title: "Using GitHub Projects",
        description: "Kanban and planning boards.",
        url: "https://www.youtube.com/watch?v=x4YJRbDeFhU",
        tags: ["beginner", "github", "project-management"],
      },
    ],
  },
  {
    id: "cloud-computing",
    name: "Cloud Computing",
    colorDot: "bg-cyan-500",
    headerBg: "bg-cyan-700",
    headerText: "text-white",
    image: "/placeholder.svg?height=100&width=100&text=Cloud", // Updated image
    difficulty: "medium",
    estimatedTime: "30-45 hours",
    items: [
      {
        id: "cloud-1",
        type: "youtube",
        title: "Intro to Cloud Computing",
        description: "Basic concepts of cloud, IaaS, PaaS, SaaS.",
        url: "https://www.youtube.com/watch?v=2LaAJq1lB1Q",
        tags: ["beginner", "cloud", "fundamentals"],
      },
      {
        id: "cloud-2",
        type: "article",
        title: "AWS vs Azure vs GCP",
        description: "Comparison of top cloud providers.",
        url: "https://kinsta.com/blog/aws-vs-azure-vs-google-cloud/",
        tags: ["intermediate", "cloud", "comparison"],
      },
      {
        id: "cloud-3",
        type: "github",
        title: "AWS Tutorials",
        description: "Beginner-friendly AWS project examples.",
        url: "https://github.com/realpython/python-systems-design",
        tags: ["resource", "aws", "cloud"],
      },
      {
        id: "cloud-4",
        type: "youtube",
        title: "Cloud Architecture Explained",
        description: "High-level deployment examples.",
        url: "https://www.youtube.com/watch?v=1UxtWm-7vVw",
        tags: ["intermediate", "cloud", "architecture"],
      },
      {
        id: "cloud-5",
        type: "article",
        title: "S3, EC2, Lambda Overview",
        description: "Core AWS services.",
        url: "https://aws.amazon.com/getting-started/hands-on/",
        tags: ["beginner", "aws", "cloud"],
      },
      {
        id: "cloud-6",
        type: "github",
        title: "Terraform Examples",
        description: "Infrastructure as code basics.",
        url: "https://github.com/hashicorp/learn-terraform-provision",
        tags: ["advanced", "cloud", "devops", "iac"],
      },
      {
        id: "cloud-7",
        type: "youtube",
        title: "Serverless Architectures",
        description: "Event-driven serverless systems.",
        url: "https://www.youtube.com/watch?v=HykWj7E3p1U",
        tags: ["intermediate", "cloud", "serverless"],
      },
      {
        id: "cloud-8",
        type: "article",
        title: "Cloud Certifications Roadmap",
        description: "AWS, Azure, GCP paths.",
        url: "https://roadmap.sh/cloud",
        tags: ["resource", "cloud", "career"],
      },
      {
        id: "cloud-9",
        type: "github",
        title: "Awesome Cloud",
        description: "Curated list of cloud learning resources.",
        url: "https://github.com/Cloud-Arch/Awesome-Cloud",
        tags: ["resource", "cloud"],
      },
    ],
  },

  // New topic 2
  {
    id: "cybersecurity",
    name: "Cybersecurity",
    colorDot: "bg-rose-500",
    headerBg: "bg-rose-700",
    headerText: "text-white",
    image: "/placeholder.svg?height=100&width=100&text=CyberSec", // Updated image
    difficulty: "medium",
    estimatedTime: "35-50 hours",
    items: [
      {
        id: "cyber-1",
        type: "youtube",
        title: "Cybersecurity Crash Course",
        description: "Fundamentals for beginners.",
        url: "https://www.youtube.com/watch?v=inWWhr5tnEA",
        tags: ["beginner", "cybersecurity", "fundamentals"],
      },
      {
        id: "cyber-2",
        type: "article",
        title: "OWASP Top 10",
        description: "Most common web security risks.",
        url: "https://owasp.org/www-project-top-ten/",
        tags: ["intermediate", "cybersecurity", "web-security"],
      },
      {
        id: "cyber-3",
        type: "github",
        title: "HackTheBox Labs",
        description: "Pen-testing virtual machines.",
        url: "https://github.com/hackthebox",
        tags: ["advanced", "cybersecurity", "practice"],
      },
      {
        id: "cyber-4",
        type: "youtube",
        title: "Intro to Ethical Hacking",
        description: "Reconnaissance, scanning, exploitation.",
        url: "https://www.youtube.com/watch?v=3Kq1MIfTWCE",
        tags: ["intermediate", "cybersecurity", "hacking"],
      },
      {
        id: "cyber-5",
        type: "article",
        title: "Encryption Basics",
        description: "Symmetric vs asymmetric encryption.",
        url: "https://www.cloudflare.com/learning/ssl/what-is-encryption/",
        tags: ["beginner", "cybersecurity", "cryptography"],
      },
      {
        id: "cyber-6",
        type: "github",
        title: "Awesome Hacking",
        description: "Resources for hacking and CTFs.",
        url: "https://github.com/Hack-with-Github/Awesome-Hacking",
        tags: ["resource", "cybersecurity", "hacking"],
      },
      {
        id: "cyber-7",
        type: "youtube",
        title: "Network Security Overview",
        description: "Firewalls, proxies, VPNs.",
        url: "https://www.youtube.com/watch?v=IrwVBhZyzK0",
        tags: ["intermediate", "cybersecurity", "networking"],
      },
      {
        id: "cyber-8",
        type: "article",
        title: "Cyber Laws & Ethics",
        description: "Legal and ethical considerations.",
        url: "https://www.geeksforgeeks.org/cyber-laws-and-it-laws-in-india/",
        tags: ["beginner", "cybersecurity", "ethics"],
      },
      {
        id: "cyber-9",
        type: "github",
        title: "Pentest Tools",
        description: "Tools for penetration testing.",
        url: "https://github.com/enaqx/awesome-pentest",
        tags: ["resource", "cybersecurity", "tools"],
      },
    ],
  },

  // New topic 3
  {
    id: "data-analysis",
    name: "Data Analysis",
    colorDot: "bg-lime-500",
    headerBg: "bg-lime-700",
    headerText: "text-white",
    image: "/placeholder.svg?height=100&width=100&text=DataAnalysis", // Updated image
    difficulty: "easy",
    estimatedTime: "25-40 hours",
    items: [
      {
        id: "da-1",
        type: "youtube",
        title: "Intro to Pandas",
        description: "Data analysis using Python.",
        url: "https://www.youtube.com/watch?v=vmEHCJofslg",
        tags: ["beginner", "data-analysis", "python"],
      },
      {
        id: "da-2",
        type: "article",
        title: "EDA Techniques",
        description: "Explore and visualize data.",
        url: "https://towardsdatascience.com/exploratory-data-analysis-8fc1cb20fd15",
        tags: ["intermediate", "data-analysis", "visualization"],
      },
      {
        id: "da-3",
        type: "github",
        title: "Pandas Exercises",
        description: "Practice data manipulation.",
        url: "https://github.com/guipsamora/pandas_exercises",
        tags: ["resource", "data-analysis", "python"],
      },
      {
        id: "da-4",
        type: "youtube",
        title: "Matplotlib & Seaborn",
        description: "Create visualizations in Python.",
        url: "https://www.youtube.com/watch?v=1jG3JuDt1p8",
        tags: ["beginner", "data-analysis", "visualization"],
      },
      {
        id: "da-5",
        type: "article",
        title: "Data Cleaning Guide",
        description: "Handle missing & duplicate data.",
        url: "https://realpython.com/python-data-cleaning-numpy-pandas/",
        tags: ["intermediate", "data-analysis", "data-prep"],
      },
      {
        id: "da-6",
        type: "github",
        title: "EDA Templates",
        description: "Starter notebooks for projects.",
        url: "https://github.com/danielrapp/EDA-templates",
        tags: ["resource", "data-analysis", "project"],
      },
      {
        id: "da-7",
        type: "youtube",
        title: "Data Wrangling",
        description: "Cleaning and structuring messy data.",
        url: "https://www.youtube.com/watch?v=vmEHCJofslg",
        tags: ["intermediate", "data-analysis", "data-prep"],
      },
      {
        id: "da-8",
        type: "article",
        title: "Correlation vs Causation",
        description: "Interpret your data correctly.",
        url: "https://www.tylervigen.com/spurious-correlations",
        tags: ["beginner", "data-analysis", "statistics"],
      },
      {
        id: "da-9",
        type: "github",
        title: "Awesome Data Analysis",
        description: "Curated list of analysis tools.",
        url: "https://github.com/josephmisiti/awesome-machine-learning#data-analysis",
        tags: ["resource", "data-analysis", "tools"],
      },
    ],
  },

  // New topic 4
  {
    id: "python-foundations",
    name: "Python Programming",
    colorDot: "bg-indigo-500",
    headerBg: "bg-indigo-700",
    headerText: "text-white",
    image: "/placeholder.svg?height=100&width=100&text=Python", // Updated image
    difficulty: "easy",
    estimatedTime: "20-30 hours",
    items: [
      {
        id: "py-1",
        type: "youtube",
        title: "Python Full Course",
        description: "Beginner to advanced Python.",
        url: "https://www.youtube.com/watch?v=rfscVS0vtbw",
        tags: ["beginner", "python", "fundamentals"],
      },
      {
        id: "py-2",
        type: "article",
        title: "Python Cheat Sheet",
        description: "Quick syntax reference.",
        url: "https://www.datacamp.com/blog/python-cheat-sheet",
        tags: ["resource", "python"],
      },
      {
        id: "py-3",
        type: "github",
        title: "100 Python Projects",
        description: "Mini projects for practice.",
        url: "https://github.com/Python-World/python-mini-projects",
        tags: ["beginner", "python", "project"],
      },
      {
        id: "py-4",
        type: "youtube",
        title: "Object-Oriented Python",
        description: "Classes and inheritance.",
        url: "https://www.youtube.com/watch?v=Ej_02ICOIgs",
        tags: ["intermediate", "python", "oop"],
      },
      {
        id: "py-5",
        type: "article",
        title: "Python Tips & Tricks",
        description: "Advanced and concise tricks.",
        url: "https://towardsdatascience.com/50-python-interview-questions-7efd2db2d955",
        tags: ["advanced", "python", "interview-prep"],
      },
      {
        id: "py-6",
        type: "github",
        title: "Python Practice Book",
        description: "Code samples and exercises.",
        url: "https://github.com/anandology/python-practice-book",
        tags: ["resource", "python", "practice"],
      },
      {
        id: "py-7",
        type: "youtube",
        title: "Python Debugging & Testing",
        description: "Tools for better code.",
        url: "https://www.youtube.com/watch?v=FX443VZGeXo",
        tags: ["intermediate", "python", "testing"],
      },
      {
        id: "py-8",
        type: "article",
        title: "Comprehensions in Python",
        description: "List, dict, and set comprehensions.",
        url: "https://realpython.com/list-comprehension-python/",
        tags: ["intermediate", "python", "syntax"],
      },
      {
        id: "py-9",
        type: "github",
        title: "Python Algorithms",
        description: "Algorithm implementations in Python.",
        url: "https://github.com/TheAlgorithms/Python",
        tags: ["resource", "python", "algorithm"],
      },
    ],
  },

  // New topic 5
  {
    id: "android-development",
    name: "Android Development",
    colorDot: "bg-emerald-500",
    headerBg: "bg-emerald-700",
    headerText: "text-white",
    image: "/placeholder.svg?height=100&width=100&text=Android", // Updated image
    difficulty: "medium",
    estimatedTime: "40-60 hours",
    items: [
      {
        id: "android-1",
        type: "youtube",
        title: "Android Dev Tutorial",
        description: "Build apps with Kotlin.",
        url: "https://www.youtube.com/watch?v=BBWyXo-3JGQ",
        tags: ["beginner", "android", "kotlin"],
      },
      {
        id: "android-2",
        type: "article",
        title: "Kotlin for Android",
        description: "Modern language for Android dev.",
        url: "https://developer.android.com/kotlin",
        tags: ["beginner", "android", "kotlin"],
      },
      {
        id: "android-3",
        type: "github",
        title: "Android Projects",
        description: "Beginner-friendly apps.",
        url: "https://github.com/AndroidDevBR/awesome-android-kotlin",
        tags: ["resource", "android", "project"],
      },
      {
        id: "android-4",
        type: "youtube",
        title: "Jetpack Compose Basics",
        description: "Modern UI toolkit for Android.",
        url: "https://www.youtube.com/watch?v=OZTFGZbrU2g",
        tags: ["intermediate", "android", "ui"],
      },
      {
        id: "android-5",
        type: "article",
        title: "Material Design in Android",
        description: "Best practices for UI/UX.",
        url: "https://m3.material.io/",
        tags: ["intermediate", "android", "ui", "ux"],
      },
      {
        id: "android-6",
        type: "github",
        title: "Jetpack Samples",
        description: "Examples for architecture components.",
        url: "https://github.com/android/sunflower",
        tags: ["resource", "android", "architecture"],
      },
      {
        id: "android-7",
        type: "youtube",
        title: "Firebase for Android",
        description: "Real-time DB, auth, and analytics.",
        url: "https://www.youtube.com/watch?v=w-U_99zLzo8",
        tags: ["intermediate", "android", "backend", "firebase"],
      },
      {
        id: "android-8",
        type: "article",
        title: "Publishing to Play Store",
        description: "Steps to release your app.",
        url: "https://developer.android.com/studio/publish",
        tags: ["advanced", "android", "deployment"],
      },
      {
        id: "android-9",
        type: "github",
        title: "Awesome Android UI",
        description: "Curated UI components and designs.",
        url: "https://github.com/wasabeef/awesome-android-ui",
        tags: ["resource", "android", "ui"],
      },
    ],
  },
]
